using System.Text;
using IronMapper.Generator.Analysis.Models;

namespace IronMapper.Generator.CodeGeneration;

internal static class MapperCodeEmitter
{
    /// <summary>
    /// Generates the source text for a single mapping and returns it together with a unique hint name.
    /// </summary>
    public static (string hintName, string source) Emit(MappingDescriptor descriptor)
    {
        var sourceFullName = GetFullTypeName(descriptor.SourceNamespace, descriptor.SourceTypeName);
        var destFullName = GetFullTypeName(descriptor.DestNamespace, descriptor.DestTypeName);
        var methodName = $"MapTo{descriptor.DestTypeName}";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace IronMapper.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class GeneratedMappers");
        sb.AppendLine("    {");
        sb.AppendLine($"        /// <summary>Maps <see cref=\"{EscapeXml(sourceFullName)}\"/> to <see cref=\"{EscapeXml(destFullName)}\"/>.</summary>");
        sb.AppendLine($"        /// <param name=\"source\">The source <see cref=\"{EscapeXml(sourceFullName)}\"/> instance to map.</param>");
        sb.AppendLine($"        /// <returns>A new <see cref=\"{EscapeXml(destFullName)}\"/> populated from <paramref name=\"source\"/>.</returns>");
        sb.AppendLine($"        public static {destFullName} {methodName}(this {sourceFullName} source)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (source is null) throw new global::System.ArgumentNullException(nameof(source));");

        // When() guard — emit before the object initializer.
        if (descriptor.WhenConditionBody is not null)
        {
            sb.AppendLine($"            if (!({descriptor.WhenConditionBody})) return default!;");
        }

        sb.AppendLine($"            return new {destFullName}");
        sb.AppendLine("            {");

        foreach (var prop in descriptor.PropertyMappings)
        {
            if (prop.IsIgnored) continue;

            if (prop.LambdaBody is not null)
            {
                // ForMember(..., opt => opt.MapFrom(src => <body>)) — emit lambda body verbatim.
                sb.AppendLine($"                {prop.DestPropertyName} = {prop.LambdaBody},");
            }
            else if (prop.ConverterType is not null)
            {
                sb.AppendLine($"                {prop.DestPropertyName} = new global::{prop.ConverterType}().Convert(source.{prop.SourcePropertyName}),");
            }
            else
            {
                sb.AppendLine($"                {prop.DestPropertyName} = source.{prop.SourcePropertyName},");
            }
        }

        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        var ns = descriptor.SourceNamespace is null
            ? string.Empty
            : descriptor.SourceNamespace.Replace('.', '_') + "_";
        var hintName = $"{ns}{descriptor.SourceTypeName}_MapTo{descriptor.DestTypeName}.g.cs";

        return (hintName, sb.ToString());
    }

    private static string GetFullTypeName(string? namespaceName, string typeName)
        => namespaceName is null
            ? $"global::{typeName}"
            : $"global::{namespaceName}.{typeName}";

    /// <summary>Escapes angle brackets so the name is safe inside an XML doc comment.</summary>
    private static string EscapeXml(string value)
        => value.Replace("<", "&lt;").Replace(">", "&gt;");
}
