using System.Text;
using IronMapper.Generator.Analysis.Models;

namespace IronMapper.Generator.CodeGeneration;

/// <summary>
/// Converts a <see cref="MappingDescriptor"/> into a C# source file containing the mapping
/// extension methods inside <c>IronMapper.Generated.GeneratedMappers</c>.
/// </summary>
/// <remarks>
/// For each mapping the emitter generates four methods:
/// <list type="bullet">
///   <item><c>MapToDestType(this SourceType source) → DestType</c> — creates a new instance.</item>
///   <item><c>MapToDestType(this SourceType source, DestType destination) → void</c> — in-place update (skips init-only properties).</item>
///   <item><c>MapToDestTypeList(this IEnumerable&lt;SourceType&gt;? source) → List&lt;DestType&gt;</c> — collection shorthand.</item>
///   <item><c>MapToDestTypeArray(this IEnumerable&lt;SourceType&gt;? source) → DestType[]</c> — collection shorthand.</item>
/// </list>
/// </remarks>
internal static class MapperCodeEmitter
{
    /// <summary>
    /// Generates the source text for a single mapping and returns it together with a unique hint name.
    /// </summary>
    public static (string hintName, string source) Emit(MappingDescriptor descriptor)
    {
        var sourceFullName = GetFullTypeName(descriptor.SourceNamespace, descriptor.SourceTypeName);
        var destFullName   = GetFullTypeName(descriptor.DestNamespace,   descriptor.DestTypeName);
        var methodName     = $"MapTo{descriptor.DestTypeName}";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace IronMapper.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class GeneratedMappers");
        sb.AppendLine("    {");

        // ------------------------------------------------------------------
        // Method 1: MapToDestType(this SourceType source) → DestType
        // ------------------------------------------------------------------
        sb.AppendLine($"        /// <summary>Maps <see cref=\"{EscapeXml(sourceFullName)}\"/> to a new <see cref=\"{EscapeXml(destFullName)}\"/>.</summary>");
        sb.AppendLine($"        /// <param name=\"source\">The source <see cref=\"{EscapeXml(sourceFullName)}\"/> instance to map.</param>");
        sb.AppendLine($"        /// <returns>A new <see cref=\"{EscapeXml(destFullName)}\"/> populated from <paramref name=\"source\"/>.</returns>");
        sb.AppendLine($"        public static {destFullName} {methodName}(this {sourceFullName} source)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (source is null) throw new global::System.ArgumentNullException(nameof(source));");

        if (descriptor.WhenConditionBody is not null)
            sb.AppendLine($"            if (!({descriptor.WhenConditionBody})) return default!;");

        if (descriptor.WholeObjectConverterType is not null)
        {
            sb.AppendLine($"            return new global::{descriptor.WholeObjectConverterType}().Convert(source);");
        }
        else if (descriptor.WholeObjectLambdaBody is not null)
        {
            sb.AppendLine($"            return {descriptor.WholeObjectLambdaBody};");
        }
        else
        {
            sb.AppendLine($"            return new {destFullName}");
            sb.AppendLine("            {");
            foreach (var prop in descriptor.PropertyMappings)
            {
                if (prop.IsIgnored) continue;
                sb.Append("                ");
                sb.AppendLine(BuildPropertyInitializer(prop) + ",");
            }
            sb.AppendLine("            };");
        }

        sb.AppendLine("        }");

        // ------------------------------------------------------------------
        // Method 2: MapToDestType(this SourceType source, DestType destination) → void  [in-place]
        // ------------------------------------------------------------------
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>Maps <see cref=\"{EscapeXml(sourceFullName)}\"/> into an existing <see cref=\"{EscapeXml(destFullName)}\"/> instance.</summary>");
        sb.AppendLine($"        /// <param name=\"source\">The source <see cref=\"{EscapeXml(sourceFullName)}\"/> to read from.</param>");
        sb.AppendLine($"        /// <param name=\"destination\">The <see cref=\"{EscapeXml(destFullName)}\"/> instance to populate. Init-only properties are not updated.</param>");
        sb.AppendLine($"        public static void {methodName}(this {sourceFullName} source, {destFullName} destination)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (source is null) throw new global::System.ArgumentNullException(nameof(source));");
        sb.AppendLine("            if (destination is null) throw new global::System.ArgumentNullException(nameof(destination));");
        foreach (var prop in descriptor.PropertyMappings)
        {
            if (prop.IsIgnored || prop.IsInitOnly) continue;
            sb.AppendLine($"            destination.{prop.DestPropertyName} = {BuildRhs(prop)};");
        }
        sb.AppendLine("        }");

        // ------------------------------------------------------------------
        // Method 3: MapToDestTypeList(this IEnumerable<SourceType>? source) → List<DestType>
        // ------------------------------------------------------------------
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>Maps each element of <paramref name=\"source\"/> to <see cref=\"{EscapeXml(destFullName)}\"/> and returns a <see cref=\"global::System.Collections.Generic.List{{T}}\"/>.</summary>");
        sb.AppendLine($"        public static global::System.Collections.Generic.List<{destFullName}> {methodName}List(this global::System.Collections.Generic.IEnumerable<{sourceFullName}>? source)");
        sb.AppendLine($"            => source is null");
        sb.AppendLine($"                ? new global::System.Collections.Generic.List<{destFullName}>()");
        sb.AppendLine($"                : global::System.Linq.Enumerable.ToList(global::System.Linq.Enumerable.Select(source, x => x.{methodName}()));");

        // ------------------------------------------------------------------
        // Method 4: MapToDestTypeArray(this IEnumerable<SourceType>? source) → DestType[]
        // ------------------------------------------------------------------
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>Maps each element of <paramref name=\"source\"/> to <see cref=\"{EscapeXml(destFullName)}\"/> and returns an array.</summary>");
        sb.AppendLine($"        public static {destFullName}[] {methodName}Array(this global::System.Collections.Generic.IEnumerable<{sourceFullName}>? source)");
        sb.AppendLine($"            => source is null");
        sb.AppendLine($"                ? global::System.Array.Empty<{destFullName}>()");
        sb.AppendLine($"                : global::System.Linq.Enumerable.ToArray(global::System.Linq.Enumerable.Select(source, x => x.{methodName}()));");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        var ns = descriptor.SourceNamespace is null
            ? string.Empty
            : descriptor.SourceNamespace.Replace('.', '_') + "_";
        var hintName = $"{ns}{descriptor.SourceTypeName}_MapTo{descriptor.DestTypeName}.g.cs";

        return (hintName, sb.ToString());
    }

    // -----------------------------------------------------------------------
    // Property emission helpers
    // -----------------------------------------------------------------------

    /// <summary>
    /// Builds an object-initializer line: <c>PropName = &lt;rhs&gt;</c>.
    /// </summary>
    private static string BuildPropertyInitializer(PropertyMappingDescriptor prop)
        => $"{prop.DestPropertyName} = {BuildRhs(prop)}";

    /// <summary>
    /// Builds the right-hand side expression for a property mapping.
    /// </summary>
    private static string BuildRhs(PropertyMappingDescriptor prop)
    {
        if (prop.LambdaBody is not null)
            return prop.LambdaBody;

        if (prop.ConverterType is not null)
            return $"new global::{prop.ConverterType}().Convert(source.{prop.SourcePropertyName})";

        if (prop.CollectionElementMapMethod is not null)
            return BuildCollectionRhs(prop);

        return $"source.{prop.SourcePropertyName}";
    }

    /// <summary>
    /// Builds the RHS for a nested collection property, emitting a null-guard and a LINQ Select.
    /// </summary>
    private static string BuildCollectionRhs(PropertyMappingDescriptor prop)
    {
        var srcExpr    = $"source.{prop.SourcePropertyName}";
        var selectExpr = $"global::System.Linq.Enumerable.Select({srcExpr}, x => x.{prop.CollectionElementMapMethod}())";

        return prop.CollectionOutputType switch
        {
            "Array" =>
                $"{srcExpr} is null ? null! : global::System.Linq.Enumerable.ToArray({selectExpr})",
            "List" =>
                $"{srcExpr} is null ? null! : global::System.Linq.Enumerable.ToList({selectExpr})",
            _ =>
                $"{srcExpr} is null ? null! : {selectExpr}",
        };
    }

    // -----------------------------------------------------------------------
    // Utilities
    // -----------------------------------------------------------------------

    private static string GetFullTypeName(string? namespaceName, string typeName)
        => namespaceName is null
            ? $"global::{typeName}"
            : $"global::{namespaceName}.{typeName}";

    /// <summary>Escapes angle brackets so the name is safe inside an XML doc comment.</summary>
    private static string EscapeXml(string value)
        => value.Replace("<", "&lt;").Replace(">", "&gt;");
}
