using System.Collections.Immutable;
using System.Text;
using IronMapper.Generator.Analysis.Models;

namespace IronMapper.Generator.CodeGeneration;

/// <summary>
/// Converts a <see cref="MappingDescriptor"/> into a C# source file containing the mapping
/// extension methods inside <c>IronMapper.Generated.GeneratedMappers</c>.
/// </summary>
/// <remarks>
/// For each mapping the emitter generates four methods:
/// <list type="bullet">
///   <item><c>MapToDestType(this SourceType source) → DestType</c> — creates a new instance.</item>
///   <item><c>MapToDestType(this SourceType source, DestType destination) → void</c> — in-place update (skips init-only properties).</item>
///   <item><c>MapToDestTypeList(this IEnumerable&lt;SourceType&gt;? source) → List&lt;DestType&gt;</c> — collection shorthand.</item>
///   <item><c>MapToDestTypeArray(this IEnumerable&lt;SourceType&gt;? source) → DestType[]</c> — collection shorthand.</item>
/// </list>
/// </remarks>
internal static class MapperCodeEmitter
{
    /// <summary>
    /// Generates the source text for a single mapping and returns it together with a unique hint name.
    /// </summary>
    /// <returns>
    /// A tuple of <c>(hintName, source)</c> where <c>hintName</c> is used as the AddSource key
    /// and <c>source</c> is the full C# text of the generated file.
    /// </returns>
    public static (string hintName, string source) Emit(MappingDescriptor descriptor)
    {
        var sourceFullName = GetFullTypeName(descriptor.SourceNamespace, descriptor.SourceTypeName);
        var destFullName   = GetFullTypeName(descriptor.DestNamespace,   descriptor.DestTypeName);
        var methodName     = $"MapTo{descriptor.DestTypeName}";

        // Scope transformer method names to this mapping to avoid CS0111 conflicts
        // when multiple profiles in the same compilation register the same transformer type.
        var scope = $"_{descriptor.SourceTypeName}_{descriptor.DestTypeName}";
        var scopedTransformers = ScopeTransformers(descriptor.ValueTransformers, scope);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace IronMapper.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class GeneratedMappers");
        sb.AppendLine("    {");

        // ------------------------------------------------------------------
        // Method 1: MapToDestType(this SourceType source) → DestType
        // ------------------------------------------------------------------
        sb.AppendLine($"        /// <summary>Maps <see cref=\"{EscapeXml(sourceFullName)}\"/> to a new <see cref=\"{EscapeXml(destFullName)}\"/>.</summary>");
        sb.AppendLine($"        /// <param name=\"source\">The source <see cref=\"{EscapeXml(sourceFullName)}\"/> instance to map.</param>");
        sb.AppendLine($"        /// <returns>A new <see cref=\"{EscapeXml(destFullName)}\"/> populated from <paramref name=\"source\"/>.</returns>");
        sb.AppendLine($"        public static {destFullName} {methodName}(this {sourceFullName} source)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (source is null) throw new global::System.ArgumentNullException(nameof(source));");

        if (descriptor.WhenConditionBody is not null)
            sb.AppendLine($"            if (!({descriptor.WhenConditionBody})) return default!;"); // safe: `default!` is part of the emitted C# text, not a local operator

        var hasHooks = descriptor.BeforeMapLambdaBody is not null || descriptor.AfterMapLambdaBody is not null;
        var beforeMapMethodName = $"BeforeMap_{descriptor.SourceTypeName}_{descriptor.DestTypeName}";
        var afterMapMethodName  = $"AfterMap_{descriptor.SourceTypeName}_{descriptor.DestTypeName}";

        if (descriptor.WholeObjectConverterType is not null)
        {
            sb.AppendLine($"            return new global::{descriptor.WholeObjectConverterType}().Convert(source);");
        }
        else if (descriptor.WholeObjectLambdaBody is not null)
        {
            sb.AppendLine($"            return {descriptor.WholeObjectLambdaBody};");
        }
        else if (hasHooks)
        {
            // Two-step pattern required when BeforeMap or AfterMap hooks are present.
            sb.AppendLine($"            var destination = new {destFullName}();");

            if (descriptor.BeforeMapLambdaBody is not null)
                sb.AppendLine($"            {beforeMapMethodName}(source, destination);");

            foreach (var prop in descriptor.PropertyMappings)
            {
                if (prop.IsIgnored || prop.IsInitOnly) continue;
                sb.AppendLine($"            destination.{prop.DestPropertyName} = {BuildRhs(prop, scopedTransformers)};");
            }

            if (descriptor.AfterMapLambdaBody is not null)
                sb.AppendLine($"            {afterMapMethodName}(source, destination);");

            sb.AppendLine("            return destination;");
        }
        else
        {
            sb.AppendLine($"            return new {destFullName}");
            sb.AppendLine("            {");
            foreach (var prop in descriptor.PropertyMappings)
            {
                if (prop.IsIgnored) continue;
                sb.Append("                ");
                sb.AppendLine(BuildPropertyInitializer(prop, scopedTransformers) + ",");
            }
            sb.AppendLine("            };");
        }

        sb.AppendLine("        }");

        // ------------------------------------------------------------------
        // Method 2: MapToDestType(this SourceType source, DestType destination) → void  [in-place]
        // ------------------------------------------------------------------
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>Maps <see cref=\"{EscapeXml(sourceFullName)}\"/> into an existing <see cref=\"{EscapeXml(destFullName)}\"/> instance.</summary>");
        sb.AppendLine($"        /// <param name=\"source\">The source <see cref=\"{EscapeXml(sourceFullName)}\"/> to read from.</param>");
        sb.AppendLine($"        /// <param name=\"destination\">The <see cref=\"{EscapeXml(destFullName)}\"/> instance to populate. Init-only properties are not updated.</param>");
        sb.AppendLine($"        public static void {methodName}(this {sourceFullName} source, {destFullName} destination)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (source is null) throw new global::System.ArgumentNullException(nameof(source));");
        sb.AppendLine("            if (destination is null) throw new global::System.ArgumentNullException(nameof(destination));");
        foreach (var prop in descriptor.PropertyMappings)
        {
            if (prop.IsIgnored || prop.IsInitOnly) continue;
            sb.AppendLine($"            destination.{prop.DestPropertyName} = {BuildRhs(prop, scopedTransformers)};");
        }
        sb.AppendLine("        }");

        // ------------------------------------------------------------------
        // Method 3: MapToDestTypeList(this IEnumerable<SourceType>? source) → List<DestType>
        // ------------------------------------------------------------------
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>Maps each element of <paramref name=\"source\"/> to <see cref=\"{EscapeXml(destFullName)}\"/> and returns a <see cref=\"global::System.Collections.Generic.List{{T}}\"/>.</summary>");
        sb.AppendLine($"        public static global::System.Collections.Generic.List<{destFullName}> {methodName}List(this global::System.Collections.Generic.IEnumerable<{sourceFullName}>? source)");
        sb.AppendLine($"            => source is null");
        sb.AppendLine($"                ? new global::System.Collections.Generic.List<{destFullName}>()");
        sb.AppendLine($"                : global::System.Linq.Enumerable.ToList(global::System.Linq.Enumerable.Select(source, x => x.{methodName}()));");

        // ------------------------------------------------------------------
        // Method 4: MapToDestTypeArray(this IEnumerable<SourceType>? source) → DestType[]
        // ------------------------------------------------------------------
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>Maps each element of <paramref name=\"source\"/> to <see cref=\"{EscapeXml(destFullName)}\"/> and returns an array.</summary>");
        sb.AppendLine($"        public static {destFullName}[] {methodName}Array(this global::System.Collections.Generic.IEnumerable<{sourceFullName}>? source)");
        sb.AppendLine($"            => source is null");
        sb.AppendLine($"                ? global::System.Array.Empty<{destFullName}>()");
        sb.AppendLine($"                : global::System.Linq.Enumerable.ToArray(global::System.Linq.Enumerable.Select(source, x => x.{methodName}()));");

        // ------------------------------------------------------------------
        // Private hook helpers (only emitted when BeforeMap/AfterMap are set)
        // ------------------------------------------------------------------
        if (descriptor.BeforeMapLambdaBody is not null)
        {
            sb.AppendLine();
            sb.AppendLine($"        private static void {beforeMapMethodName}({sourceFullName} source, {destFullName} destination)");
            sb.AppendLine("        {");
            foreach (var line in descriptor.BeforeMapLambdaBody.Split('\n'))
                sb.AppendLine($"            {line.TrimEnd()}");
            sb.AppendLine("        }");
        }

        if (descriptor.AfterMapLambdaBody is not null)
        {
            sb.AppendLine();
            sb.AppendLine($"        private static void {afterMapMethodName}({sourceFullName} source, {destFullName} destination)");
            sb.AppendLine("        {");
            foreach (var line in descriptor.AfterMapLambdaBody.Split('\n'))
                sb.AppendLine($"            {line.TrimEnd()}");
            sb.AppendLine("        }");
        }

        foreach (var t in scopedTransformers)
        {
            var fqn = t.FullyQualifiedTypeName;
            sb.AppendLine();
            if (t.LambdaBody.TrimStart().StartsWith("{", System.StringComparison.Ordinal))
            {
                var trimmedBody = t.LambdaBody.Trim();
                var blockContent = trimmedBody.Substring(1, trimmedBody.Length - 2).Trim();
                sb.AppendLine($"        private static {fqn} {t.MethodName}({fqn} value)");
                sb.AppendLine("        {");
                foreach (var line in blockContent.Split('\n'))
                    sb.AppendLine($"            {line.TrimStart()}");
                sb.AppendLine("        }");
            }
            else
            {
                sb.AppendLine($"        private static {fqn} {t.MethodName}({fqn} value) => {t.LambdaBody};");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        var ns = descriptor.SourceNamespace is null
            ? string.Empty
            : descriptor.SourceNamespace.Replace('.', '_') + "_";
        var hintName = $"{ns}{descriptor.SourceTypeName}_MapTo{descriptor.DestTypeName}.g.cs";

        return (hintName, sb.ToString());
    }

    // -----------------------------------------------------------------------
    // Property emission helpers
    // -----------------------------------------------------------------------

    /// <summary>
    /// Builds an object-initializer line: <c>PropName = &lt;rhs&gt;</c>.
    /// </summary>
    private static string BuildPropertyInitializer(PropertyMappingDescriptor prop,
        ImmutableArray<ValueTransformerDescriptor> transformers)
        => $"{prop.DestPropertyName} = {BuildRhs(prop, transformers)}";

    /// <summary>
    /// Builds the right-hand side expression for a property mapping.
    /// </summary>
    private static string BuildRhs(PropertyMappingDescriptor prop,
        ImmutableArray<ValueTransformerDescriptor> transformers)
    {
        string raw;
        if (prop.LambdaBody is not null)
            raw = prop.LambdaBody;
        else if (prop.ConverterType is not null)
            raw = $"new global::{prop.ConverterType}().Convert(source.{prop.SourcePropertyName})";
        else if (prop.CollectionElementMapMethod is not null)
            raw = BuildCollectionRhs(prop);
        else
            raw = $"source.{prop.SourcePropertyName}";

        // Apply transformer if type matches and no explicit custom mapping.
        if (prop.LambdaBody is null && prop.SourcePropertyTypeFqn is not null)
        {
            foreach (var t in transformers)
            {
                if (t.FullyQualifiedTypeName == prop.SourcePropertyTypeFqn)
                    return $"{t.MethodName}({raw})";
            }
        }

        return raw;
    }

    /// <summary>
    /// Builds the RHS for a nested collection property, emitting a null-guard and a LINQ Select.
    /// </summary>
    private static string BuildCollectionRhs(PropertyMappingDescriptor prop)
    {
        var srcExpr    = $"source.{prop.SourcePropertyName}";
        var selectExpr = $"global::System.Linq.Enumerable.Select({srcExpr}, x => x.{prop.CollectionElementMapMethod}())";

        return prop.CollectionOutputType switch
        {
            "Array" =>
                $"{srcExpr} is null ? null! : global::System.Linq.Enumerable.ToArray({selectExpr})", // safe: `null!` is part of the emitted C# text
            "List" =>
                $"{srcExpr} is null ? null! : global::System.Linq.Enumerable.ToList({selectExpr})", // safe: `null!` is part of the emitted C# text
            _ =>
                $"{srcExpr} is null ? null! : {selectExpr}", // safe: `null!` is part of the emitted C# text
        };
    }

    // -----------------------------------------------------------------------
    // Utilities
    // -----------------------------------------------------------------------

    private static ImmutableArray<ValueTransformerDescriptor> ScopeTransformers(
        ImmutableArray<ValueTransformerDescriptor> transformers, string scope)
    {
        if (transformers.IsEmpty) return transformers;
        var builder = ImmutableArray.CreateBuilder<ValueTransformerDescriptor>(transformers.Length);
        foreach (var t in transformers)
            builder.Add(new ValueTransformerDescriptor(
                t.FullyQualifiedTypeName, t.FriendlyTypeName, t.LambdaBody, t.MethodName + scope));
        return builder.ToImmutable();
    }

    private static string GetFullTypeName(string? namespaceName, string typeName)
        => namespaceName is null
            ? $"global::{typeName}"
            : $"global::{namespaceName}.{typeName}";

    /// <summary>Escapes angle brackets so the name is safe inside an XML doc comment.</summary>
    private static string EscapeXml(string value)
        => value.Replace("<", "&lt;").Replace(">", "&gt;");
}
