using System.Linq;
using Microsoft.CodeAnalysis;
using Xunit;

namespace IronMapper.Generator.Tests;

public class BasicGeneratorTests
{
    // ------------------------------------------------------------------
    // TestSimpleMapping
    // ------------------------------------------------------------------

    [Fact]
    public void TestSimpleMapping_GeneratesMapToMethod()
    {
        var source = """
            using IronMapper.Attributes;

            [MapTo(typeof(DestClass))]
            public class SourceClass
            {
                public string Name { get; set; } = "";
                public int Age { get; set; }
            }

            public class DestClass
            {
                public string Name { get; set; } = "";
                public int Age { get; set; }
            }
            """;

        var (generatedSources, diagnostics) = GeneratorTestHelper.RunGenerator(source);

        var errors = diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToList();
        Assert.Empty(errors);

        Assert.NotEmpty(generatedSources);
        var code = string.Join("\n", generatedSources);
        Assert.Contains("MapToDestClass", code);
        Assert.Contains("Name = source.Name", code);
        Assert.Contains("Age = source.Age", code);
        Assert.Contains("IronMapper.Generated", code);
        Assert.Contains("// <auto-generated/>", code);
    }

    [Fact]
    public void TestSimpleMapping_GeneratedCodeHasNullGuard()
    {
        var source = """
            using IronMapper.Attributes;

            [MapTo(typeof(Dto))]
            public class Entity { public int Id { get; set; } }
            public class Dto     { public int Id { get; set; } }
            """;

        var (generatedSources, _) = GeneratorTestHelper.RunGenerator(source);

        var code = string.Join("\n", generatedSources);
        Assert.Contains("ArgumentNullException", code);
    }

    // ------------------------------------------------------------------
    // TestPropertyNameMapping ([MapProperty])
    // ------------------------------------------------------------------

    [Fact]
    public void TestPropertyNameMapping_RenamesProperty()
    {
        var source = """
            using IronMapper.Attributes;

            [MapTo(typeof(PersonDto))]
            public class Person
            {
                [MapProperty("FullName")]
                public string Name { get; set; } = "";
            }

            public class PersonDto
            {
                public string FullName { get; set; } = "";
            }
            """;

        var (generatedSources, diagnostics) = GeneratorTestHelper.RunGenerator(source);

        var errors = diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToList();
        Assert.Empty(errors);

        var code = string.Join("\n", generatedSources);
        Assert.Contains("FullName = source.Name", code);
        // "Name" (the source property) should not appear as a destination property name.
        // Check there is no assignment of the form "  Name = source." (a dest prop named Name).
        Assert.DoesNotContain("                Name = source.", code);
    }

    // ------------------------------------------------------------------
    // TestIgnoreAttribute ([Ignore])
    // ------------------------------------------------------------------

    [Fact]
    public void TestIgnoreAttribute_PropertyNotMapped()
    {
        var source = """
            using IronMapper.Attributes;

            [MapTo(typeof(OrderDto))]
            public class Order
            {
                public int Id { get; set; }

                [Ignore]
                public string InternalToken { get; set; } = "";
            }

            public class OrderDto
            {
                public int Id { get; set; }
            }
            """;

        var (generatedSources, diagnostics) = GeneratorTestHelper.RunGenerator(source);

        var errors = diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToList();
        Assert.Empty(errors);

        var code = string.Join("\n", generatedSources);
        Assert.Contains("Id = source.Id", code);
        Assert.DoesNotContain("InternalToken", code);
    }

    // ------------------------------------------------------------------
    // TestDiagnosticMissingProperty (IM0001)
    // ------------------------------------------------------------------

    [Fact]
    public void TestDiagnosticMissingProperty_EmitsIM0001Warning()
    {
        // DestClass has ExtraProperty that doesn't exist on SourceClass.
        var source = """
            using IronMapper.Attributes;

            [MapTo(typeof(DestClass))]
            public class SourceClass
            {
                public string Name { get; set; } = "";
            }

            public class DestClass
            {
                public string Name { get; set; } = "";
                public int ExtraProperty { get; set; }
            }
            """;

        var (generatedSources, diagnostics) = GeneratorTestHelper.RunGenerator(source);

        // Code is still generated (partial mapping).
        Assert.NotEmpty(generatedSources);

        var im0001 = diagnostics.Where(d => d.Id == "IM0001").ToList();
        Assert.NotEmpty(im0001);
        Assert.Contains(im0001, d => d.GetMessage().Contains("ExtraProperty"));
    }

    // ------------------------------------------------------------------
    // TestMapFrom ([MapFrom])
    // ------------------------------------------------------------------

    [Fact]
    public void TestMapFrom_GeneratesMapToMethod()
    {
        var source = """
            using IronMapper.Attributes;

            public class UserEntity
            {
                public string Username { get; set; } = "";
            }

            [MapFrom(typeof(UserEntity))]
            public class UserDto
            {
                public string Username { get; set; } = "";
            }
            """;

        var (generatedSources, diagnostics) = GeneratorTestHelper.RunGenerator(source);

        var errors = diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToList();
        Assert.Empty(errors);

        var code = string.Join("\n", generatedSources);
        Assert.Contains("MapToUserDto", code);
        Assert.Contains("Username = source.Username", code);
    }

    // ------------------------------------------------------------------
    // TestMultipleMapTo (AllowMultiple)
    // ------------------------------------------------------------------

    [Fact]
    public void TestMultipleMapTo_GeneratesTwoMethods()
    {
        var source = """
            using IronMapper.Attributes;

            [MapTo(typeof(DestA))]
            [MapTo(typeof(DestB))]
            public class Source
            {
                public int Value { get; set; }
            }

            public class DestA { public int Value { get; set; } }
            public class DestB { public int Value { get; set; } }
            """;

        var (generatedSources, diagnostics) = GeneratorTestHelper.RunGenerator(source);

        var errors = diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToList();
        Assert.Empty(errors);

        var code = string.Join("\n", generatedSources);
        Assert.Contains("MapToDestA", code);
        Assert.Contains("MapToDestB", code);
    }
}
