using System.Linq;
using Microsoft.CodeAnalysis;
using Xunit;

namespace IronMapper.Generator.Tests;

public class BasicGeneratorTests
{
    // ------------------------------------------------------------------
    // Simple mapping
    // ------------------------------------------------------------------

    [Fact]
    public void SimpleMapping_WhenMapToAttributeApplied_GeneratesMapToExtensionMethod()
    {
        var source = """
            using IronMapper.Attributes;

            [MapTo(typeof(DestClass))]
            public class SourceClass
            {
                public string Name { get; set; } = "";
                public int Age { get; set; }
            }

            public class DestClass
            {
                public string Name { get; set; } = "";
                public int Age { get; set; }
            }
            """;

        var (generatedSources, diagnostics) = GeneratorTestHelper.RunGenerator(source);

        Assert.DoesNotContain(diagnostics, d => d.Severity == DiagnosticSeverity.Error);
        Assert.NotEmpty(generatedSources);
        var code = string.Join("\n", generatedSources);
        Assert.Contains("MapToDestClass", code);
        Assert.Contains("Name = source.Name", code);
        Assert.Contains("Age = source.Age", code);
        Assert.Contains("IronMapper.Generated", code);
        Assert.Contains("// <auto-generated/>", code);
    }

    [Fact]
    public void SimpleMapping_WhenSourceCouldBeNull_GeneratedCodeContainsArgumentNullGuard()
    {
        var source = """
            using IronMapper.Attributes;

            [MapTo(typeof(Dto))]
            public class Entity { public int Id { get; set; } }
            public class Dto     { public int Id { get; set; } }
            """;

        var (generatedSources, _) = GeneratorTestHelper.RunGenerator(source);

        var code = string.Join("\n", generatedSources);
        Assert.Contains("ArgumentNullException", code);
    }

    // ------------------------------------------------------------------
    // MapProperty attribute
    // ------------------------------------------------------------------

    [Fact]
    public void MapPropertyAttribute_WhenDestNameProvided_RemapsToDestPropertyName()
    {
        var source = """
            using IronMapper.Attributes;

            [MapTo(typeof(PersonDto))]
            public class Person
            {
                [MapProperty("FullName")]
                public string Name { get; set; } = "";
            }

            public class PersonDto
            {
                public string FullName { get; set; } = "";
            }
            """;

        var (generatedSources, diagnostics) = GeneratorTestHelper.RunGenerator(source);

        Assert.DoesNotContain(diagnostics, d => d.Severity == DiagnosticSeverity.Error);
        var code = string.Join("\n", generatedSources);
        Assert.Contains("FullName = source.Name", code);
        // "Name" must not appear as a destination property (only as source).
        Assert.DoesNotContain("                Name = source.", code);
    }

    // ------------------------------------------------------------------
    // Ignore attribute
    // ------------------------------------------------------------------

    [Fact]
    public void IgnoreAttribute_WhenAppliedToSourceProperty_ExcludesFromGeneratedMapping()
    {
        var source = """
            using IronMapper.Attributes;

            [MapTo(typeof(OrderDto))]
            public class Order
            {
                public int Id { get; set; }

                [Ignore]
                public string InternalToken { get; set; } = "";
            }

            public class OrderDto
            {
                public int Id { get; set; }
            }
            """;

        var (generatedSources, diagnostics) = GeneratorTestHelper.RunGenerator(source);

        Assert.DoesNotContain(diagnostics, d => d.Severity == DiagnosticSeverity.Error);
        var code = string.Join("\n", generatedSources);
        Assert.Contains("Id = source.Id", code);
        Assert.DoesNotContain("InternalToken", code);
    }

    // ------------------------------------------------------------------
    // IM0001 diagnostic
    // ------------------------------------------------------------------

    [Fact]
    public void UnmappedDestinationProperty_WhenNoSourceMatch_EmitsIM0001Diagnostic()
    {
        var source = """
            using IronMapper.Attributes;

            [MapTo(typeof(DestClass))]
            public class SourceClass
            {
                public string Name { get; set; } = "";
            }

            public class DestClass
            {
                public string Name { get; set; } = "";
                public int ExtraProperty { get; set; }
            }
            """;

        var (generatedSources, diagnostics) = GeneratorTestHelper.RunGenerator(source);

        // Partial mapping is still generated.
        Assert.NotEmpty(generatedSources);

        var im0001 = diagnostics.Where(d => d.Id == "IM0001").ToList();
        Assert.NotEmpty(im0001);
        Assert.Contains(im0001, d => d.GetMessage().Contains("ExtraProperty"));
    }

    // ------------------------------------------------------------------
    // MapFrom attribute
    // ------------------------------------------------------------------

    [Fact]
    public void MapFromAttribute_WhenAppliedToDestClass_GeneratesMapToExtensionMethod()
    {
        var source = """
            using IronMapper.Attributes;

            public class UserEntity
            {
                public string Username { get; set; } = "";
            }

            [MapFrom(typeof(UserEntity))]
            public class UserDto
            {
                public string Username { get; set; } = "";
            }
            """;

        var (generatedSources, diagnostics) = GeneratorTestHelper.RunGenerator(source);

        Assert.DoesNotContain(diagnostics, d => d.Severity == DiagnosticSeverity.Error);
        var code = string.Join("\n", generatedSources);
        Assert.Contains("MapToUserDto", code);
        Assert.Contains("Username = source.Username", code);
    }

    // ------------------------------------------------------------------
    // Multiple [MapTo] attributes
    // ------------------------------------------------------------------

    [Fact]
    public void MapToAttribute_WhenAppliedMultipleTimes_GeneratesOneMethodPerDestination()
    {
        var source = """
            using IronMapper.Attributes;

            [MapTo(typeof(DestA))]
            [MapTo(typeof(DestB))]
            public class Source
            {
                public int Value { get; set; }
            }

            public class DestA { public int Value { get; set; } }
            public class DestB { public int Value { get; set; } }
            """;

        var (generatedSources, diagnostics) = GeneratorTestHelper.RunGenerator(source);

        Assert.DoesNotContain(diagnostics, d => d.Severity == DiagnosticSeverity.Error);
        var code = string.Join("\n", generatedSources);
        Assert.Contains("MapToDestA", code);
        Assert.Contains("MapToDestB", code);
    }
}
