using System.Diagnostics;
using IronMapper.Demo.Models.Api;
using IronMapper.Demo.Services;
using IronMapper.Generated;

namespace IronMapper.Demo.Demos;

/// <summary>
/// Demonstrates collection mapping: List&lt;BookDoc&gt; → List&lt;BookSummary&gt; in one call.
/// The generated MapToBookSummaryList() iterates lazily and calls MapToBookSummary() per element.
/// </summary>
public static class Demo3_Collections
{
    public static async Task RunAsync(OpenLibraryService api)
    {
        PrintHeader("DEMO 3 — Mapping collections");

        Console.WriteLine("Searching books with query \"design patterns\"...\n");
        var response = await api.SearchBooksAsync("design patterns", 5);
        var docs = response?.Docs;

        if (docs is null || docs.Count == 0)
        {
            docs =
            [
                new() { Key = "/works/OL18991W",  Title = "Design Patterns", AuthorName = ["Gang of Four"], FirstPublishYear = 1994, EditionCount = 80  },
                new() { Key = "/works/OL2750836W", Title = "Head First Design Patterns", AuthorName = ["Eric Freeman"], FirstPublishYear = 2004, EditionCount = 30  },
                new() { Key = "/works/OL5854686W", Title = "Patterns of Enterprise Application Architecture", AuthorName = ["Martin Fowler"], FirstPublishYear = 2002, EditionCount = 40 },
                new() { Key = "/works/OL3924963W", Title = "Clean Architecture", AuthorName = ["Robert C. Martin"], FirstPublishYear = 2017, EditionCount = 25  },
                new() { Key = "/works/OL18992W",   Title = "Refactoring", AuthorName = ["Martin Fowler"], FirstPublishYear = 1999, EditionCount = 35  },
            ];
        }

        Console.ForegroundColor = ConsoleColor.Yellow;
        Console.WriteLine($"SOURCE  List<BookDoc> — {docs.Count} elements:");
        foreach (var d in docs)
            Console.WriteLine($"  {d.Key,-30}  {d.Title}");

        // ── One-line collection mapping ──────────────────────────────────────
        // MapToBookSummaryList() is generated by the Source Generator:
        //   public static List<BookSummary> MapToBookSummaryList(
        //       this IEnumerable<BookDoc>? source) => ...
        var sw = Stopwatch.StartNew();
        var summaries = docs.MapToBookSummaryList();
        sw.Stop();

        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine($"\nRESULT  List<BookSummary> — {summaries.Count} elements:");
        foreach (var s in summaries)
        {
            Console.WriteLine($"  {s.Id,-25} | {s.Title,-45} | {s.AuthorsDisplay}");
        }

        Console.ForegroundColor = ConsoleColor.Gray;
        Console.WriteLine();
        Console.WriteLine($"  Mapped {summaries.Count} books for {sw.Elapsed.TotalMilliseconds:F3} ms");
        Console.WriteLine($"  Single string: var summaries = docs.MapToBookSummaryList();");
        Console.ResetColor();
    }

    private static void PrintHeader(string title)
    {
        Console.ForegroundColor = ConsoleColor.Cyan;
        Console.WriteLine("\n" + new string('─', 60));
        Console.WriteLine($" {title}");
        Console.WriteLine(new string('─', 60));
        Console.ResetColor();
    }
}
